### ISSUE TITLE
Class "Drupal\gdpr_dumper\Commands\SqlSyncCommands" does not exist on v3.0.1

### ISSUE THREAD

**Issue by sonnykt** [druidfi/drush-gdpr-dumper#7]
After upgrading to version 3.0.1 (along with Drush 13), I'm getting the following error on all Drush commands:
```
In LegacyServiceInstantiator.php line 181:

  Class "Drupal\gdpr_dumper\Commands\SqlSyncCommands" does not exist
```

Version 3.0 removed the SqlSyncCommands (https://github.com/druidfi/drush-gdpr-dumper/compare/2.0.0...3.0.0) however its declaration in `drush.services.yml` was not cleaned up hence this error occurs.

**Comment by back-2-95** [comment]
Thanks! Merged and created a new release.
